/*

DELA LUNA, MICHELLE
DIAMZON  NEIL  ARONN S.

OPERATING SYSTEM FINAL LABORATORY: CPU SCHEDULING WITH MEMORY MANAGEMENT & PAGING
ss
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *ssss
 * @author neila
 */
public class CPU_with_MFT extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public CPU_with_MFT() {
        initComponents();
        this.setLocationRelativeTo(null);
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Gantt = new javax.swing.JTable();
        FilePath = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stopbtn = new javax.swing.JButton();
        AWT = new javax.swing.JLabel();
        ATT = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        currentSeconds = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Q2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Q1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Q3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        delaySelector = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cpuBox = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        K8_2 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        K4_1 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        K8_3 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        K8_1 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        K4_2 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        inputQueue = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jScrollPane9 = new javax.swing.JScrollPane();
        K16_1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        K16_2 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(926, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1564, 579));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        startbtn.setText("Start");
        startbtn.setEnabled(false);
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });

        Datas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job", "AT", "CBT", "FT", "TT", "WT", "Status", "Job Type", "Size(K)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Datas.setEnabled(false);
        Datas.setName(""); // NOI18N
        jScrollPane1.setViewportView(Datas);

        Gantt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Duration", "Job#"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Gantt);

        FilePath.setToolTipText("");
        FilePath.setEnabled(false);
        FilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilePathActionPerformed(evt);
            }
        });
        FilePath.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FilePathPropertyChange(evt);
            }
        });

        jButton2.setText("Choose File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Pause");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gantt Chart");

        jLabel2.setText("Average waiting time:");

        jLabel3.setText("Average turn around time:");

        jLabel4.setText("Interval(ms)");

        stopbtn.setText("Stop/Clear");
        stopbtn.setEnabled(false);
        stopbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtnActionPerformed(evt);
            }
        });

        AWT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AWT.setForeground(new java.awt.Color(255, 51, 51));
        AWT.setText("0");

        ATT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ATT.setForeground(new java.awt.Color(255, 0, 0));
        ATT.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("Dela Luna - Diamzon");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("MLQ - MFT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Timer:");

        currentSeconds.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        currentSeconds.setText("0");

        jButton5.setText("Resume");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Q2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job", "CPU Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Q2);

        Q1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job", "CPU Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Q1);

        Q3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job", "CPU Burst"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Q3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Q1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Q2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Q3");

        delaySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delaySelectorActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CPU:");

        cpuBox.setEditable(false);
        cpuBox.setBackground(new java.awt.Color(255, 255, 255));
        cpuBox.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        cpuBox.setForeground(new java.awt.Color(255, 51, 51));
        cpuBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpuBox.setText("-");

        K8_2.setEditable(false);
        K8_2.setBackground(new java.awt.Color(0, 255, 204));
        K8_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane7.setViewportView(K8_2);

        K4_1.setEditable(false);
        K4_1.setBackground(new java.awt.Color(153, 255, 204));
        K4_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane8.setViewportView(K4_1);

        K8_3.setEditable(false);
        K8_3.setBackground(new java.awt.Color(0, 255, 204));
        K8_3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane11.setViewportView(K8_3);

        K8_1.setEditable(false);
        K8_1.setBackground(new java.awt.Color(0, 255, 204));
        K8_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane12.setViewportView(K8_1);

        K4_2.setEditable(false);
        K4_2.setBackground(new java.awt.Color(153, 255, 204));
        K4_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane13.setViewportView(K4_2);

        inputQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job", "Size", "Q#", "CBT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(inputQueue);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setText("16K");

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setText("8K");

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setText("4K");

        K16_1.setEditable(false);
        K16_1.setBackground(new java.awt.Color(0, 153, 153));
        K16_1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane9.setViewportView(K16_1);

        K16_2.setEditable(false);
        K16_2.setBackground(new java.awt.Color(0, 153, 153));
        K16_2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jScrollPane6.setViewportView(K16_2);

        jButton4.setText("Back to Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(stopbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(delaySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(156, 156, 156)
                                                    .addComponent(jLabel11))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(startbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel7)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(currentSeconds))
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(18, 18, 18)
                                            .addComponent(cpuBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(130, 130, 130))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ATT)
                                            .addComponent(AWT))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delaySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)
                                .addComponent(currentSeconds)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startbtn)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stopbtn)
                            .addComponent(jButton5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(AWT))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(ATT)))
                        .addComponent(cpuBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String[] JID = new String[50];
    double[] arrivaltime = new double[50];
    double[] CBurst= new double[50];
    double[] turnaround= new double[50];
    double[] waitingtime= new double[50];
    double temp = 0;
    int totalNumberOfJobs = 0;
    int counter = 0;
    int currentjob = 0;
    int indexCount = 0;
    String lastjob = "";
    boolean doneflag= false;
    Timer t;
    int qIndicator = 0;
    int lastTime = 0;
    int state = 0;
    int neg = 0;
    //PUTS ON GANT TABLE THE TIME AND THE JOB CURRENTLY RUNNING
    private void putOnGantt(Integer Duration, Object Job){
         DefaultTableModel model = (DefaultTableModel) Gantt.getModel();
         model.addRow(new Object[]{Duration,Job.toString()});
         cpuBox.setText(Job.toString());
    }   
    //RUNTABLE ACCEPTS THE TABLE TO RUN AND TIME AND JOB AS PARAMETERS 
    private void runTable(JTable table, Integer Job, Integer time){
        table.setValueAt(Integer.parseInt(table.getValueAt(0, 1).toString())-1, Job, 1);     
        
        if (Integer.parseInt(table.getValueAt(0, 1).toString())==0){      
           // putOnGantt(time, table.getValueAt(0, 0));
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            DefaultTableModel model1 = (DefaultTableModel) Datas.getModel();           
            findSlot(Integer.parseInt(table.getValueAt(0, 0).toString())); 
            model1.setValueAt("Done",table.convertRowIndexToModel(getRowByValue(Datas,table.getValueAt(0, 0).toString())),6);
            time += 1;
            putOnGantt(time, table.getValueAt(0, 0));
            model1.setValueAt(time-Integer.parseInt(Datas.getValueAt(Datas.convertRowIndexToModel(getRowByValue(Datas,table.getValueAt(0, 0).toString())), 1).toString()),Datas.convertRowIndexToModel(getRowByValue(Datas,table.getValueAt(0, 0).toString())),4);
            model1.setValueAt(time,Datas.convertRowIndexToModel(getRowByValue(Datas,table.getValueAt(0, 0).toString())),3);
            model1.setValueAt(Integer.parseInt(Datas.getValueAt(getRowByValue(Datas,table.getValueAt(0, 0).toString()), 4).toString())-Integer.parseInt(Datas.getValueAt(getRowByValue(Datas,table.getValueAt(0, 0).toString()), 2).toString()),Datas.convertRowIndexToModel(getRowByValue(Datas,table.getValueAt(0, 0).toString())),5);
          
            model.removeRow(0);
            totalNumberOfJobs++;
            
        }
        else{
           putOnGantt(time, table.getValueAt(0, 0));
        }
       
    }
    void clearmemory(){
        K4_1.setText("");
        K4_2.setText("");
        K8_1.setText("");        
        K8_2.setText("");
        K8_3.setText("");
        K16_1.setText("");        
        K16_2.setText("");
        
    }
    void findSlot(Integer removeID){
        if (K4_1.getText().equals(removeID.toString())){
            K4_1.setText("");
        }
        if (K4_2.getText().equals(removeID.toString())){
            K4_2.setText("");
        }
        if (K8_1.getText().equals(removeID.toString())){
            K8_1.setText("");
        }
        if (K8_2.getText().equals(removeID.toString())){
            K8_2.setText("");
        }
        if (K8_3.getText().equals(removeID.toString())){
            K8_3.setText("");
        }
        if (K16_1.getText().equals(removeID.toString())){
            K16_1.setText("");
        }
        if (K16_2.getText().equals(removeID.toString())){
            K16_2.setText("");
        }
        
    }
    void addToQueue(Integer jobNumber, Integer queueNumber, Integer CBT){
        DefaultTableModel modelQ1 = (DefaultTableModel) Q1.getModel();
        DefaultTableModel modelQ2 = (DefaultTableModel) Q2.getModel();
        DefaultTableModel modelQ3 = (DefaultTableModel) Q3.getModel();
        if (queueNumber == 1){
             modelQ1.addRow(new Object[]{jobNumber, CBT}); 
        }
        if (queueNumber == 2){
             modelQ2.addRow(new Object[]{jobNumber, CBT}); 
        }
        if (queueNumber == 3){
             modelQ3.addRow(new Object[]{jobNumber, CBT}); 
        }
    }
    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        //START
        startbtn.setEnabled(false);
        jButton3.setEnabled(true);
        jButton5.setEnabled(false);
        stopbtn.setEnabled(true);
        if(FilePath.getText().length()>0){
            doneflag = false;
            qIndicator = 0;
            if(Datas.getRowCount()>0){
     //TIMER
              t = new Timer(Integer.parseInt(delaySelector.getSelectedItem().toString()), new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e){
                        doneflag = false;
        //CHECK ARRIVAL TIME
                        for (int i = 0; i < Datas.getRowCount(); i++){    
                            if(Integer.parseInt(Datas.getValueAt(i, 1).toString()) == counter){
                                DefaultTableModel model1 = (DefaultTableModel) Datas.getModel();
                                model1.setValueAt("Input Queue",Datas.convertRowIndexToModel(i) , 6);
                                DefaultTableModel model2 = (DefaultTableModel) inputQueue.getModel();
                                model2.addRow(new Object[]{Datas.getValueAt(i, 0).toString(), Datas.getValueAt(i, 8).toString(), Datas.getValueAt(i, 7), Datas.getValueAt(i, 2)});             
                            }                              
                        }
                        //MM IMPLEMENTATION MFT
                        if (inputQueue.getRowCount() > 0){
                           
                            try{
                                 DefaultTableModel model = (DefaultTableModel) inputQueue.getModel();
                            for(int x = 0; x < inputQueue.getRowCount(); x++){
                    //---------
                            if (Integer.parseInt(inputQueue.getValueAt(x,1).toString())<=4){
                                if (K4_1.getText().length()<1){
                                   K4_1.setText(inputQueue.getValueAt(x, 0).toString()); 
                                   addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                   model.removeRow(x);
                                }
                                if (K4_2.getText().length()<1){
                                    K4_2.setText(inputQueue.getValueAt(x, 0).toString());
                                    addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                    model.removeRow(x);
                                }                             
                                }
                         //------------
                            if (Integer.parseInt(inputQueue.getValueAt(x,1).toString())<=8){
                               
                                if (K8_1.getText().length()<1){
                                   K8_1.setText(inputQueue.getValueAt(x, 0).toString()); 
                                   addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                   model.removeRow(x);
                                }
                                if (K8_2.getText().length()<1){
                                    K8_2.setText(inputQueue.getValueAt(x, 0).toString());
                                    addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                    model.removeRow(x);
                                }
                                if (K8_3.getText().length()<1){
                                    K8_3.setText(inputQueue.getValueAt(x, 0).toString());
                                    addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                    model.removeRow(x);
                                }
                               }
                            //------------
                             if (Integer.parseInt(inputQueue.getValueAt(x,1).toString())<=16){
                               if (K16_1.getText().length()<1){
                                   K16_1.setText(inputQueue.getValueAt(x, 0).toString()); 
                                   addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                   model.removeRow(x);
                                }
                                if (K16_2.getText().length()<1){
                                    K16_2.setText(inputQueue.getValueAt(x, 0).toString());
                                    addToQueue(Integer.parseInt(inputQueue.getValueAt(x, 0).toString()),  Integer.parseInt(inputQueue.getValueAt(x, 2).toString()), Integer.parseInt(inputQueue.getValueAt(x, 3).toString()));                         
                                    model.removeRow(x);
                                }
                            }
                             //------------
                            }
                            }
                             catch(ArrayIndexOutOfBoundsException err ){                                  
                             }                           
                        }
                        //PRIORITY Q1>Q2>Q3 && DONEFLAG FOR RUN TABLE ONCE IN 1 SECOND
                        if (Q1.getRowCount()>0&&doneflag == false){                            
                            runTable(Q1, 0, counter);
                            doneflag = true;
                        }
                        if(Q2.getRowCount()>0&&Q1.getRowCount()==0&&doneflag == false){   
                            runTable(Q2, 0, counter);
                            doneflag = true;
                        }
                        if(Q3.getRowCount()>0&&Q1.getRowCount()==0&&Q2.getRowCount()==0&&doneflag == false){
                            runTable(Q3, 0, counter);
                            doneflag = true;
                        }
                        //IF DONE
                        if (totalNumberOfJobs==Datas.getRowCount()){
                            t.stop();
                            double att = 0;
                            double awt = 0;
                            for (int i = 0;i<Datas.getRowCount();i++){
                                att+=Double.parseDouble(Datas.getValueAt(i, 4).toString());
                                awt+=Double.parseDouble(Datas.getValueAt(i, 5).toString());
                            }
                            DecimalFormat df2 = new DecimalFormat(".##");
                            ATT.setText(String.valueOf(df2.format(att/Datas.getRowCount())));
                            AWT.setText(String.valueOf(df2.format(awt/Datas.getRowCount())));
                            cpuBox.setText("-");
                            final JPanel panel = new JPanel();
                            JOptionPane.showMessageDialog(panel, "Done.", null, WIDTH);
                            
                        }
                        
                        counter++;
                        currentSeconds.setText(String.valueOf(counter));
                        
                    }
                }); t.start();
            }
        }
        else{
                    JOptionPane.showMessageDialog(this, "No file selected.", null, WIDTH);

        }
     

    }//GEN-LAST:event_startbtnActionPerformed
    //FIND ROW WITH SPECIFIC VALUE
    int getRowByValue(JTable model, String value) {
    for (int i = 0; i < model.getRowCount(); i++) {    
            if (String.valueOf(model.getValueAt(i, 0)).equals(value)) {
                return i;
            }        
    }
    return -1;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //GET FILE
        stopbtn.doClick();
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            FilePath.setText(chooser.getSelectedFile().getAbsolutePath());
        }
        if (FilePath.getText().length()<1){
            JOptionPane.showMessageDialog(this, "No file selected.", null, WIDTH);
        }
        else{
            //JOB CHECK FOR CHECKING THE VALIDITY OF TEST FILE
            if(JobCheck(FilePath.getText())){
                try {
                    DefaultTableModel model = (DefaultTableModel) Datas.getModel();
                    model.setRowCount(0);
                    File f = new File(FilePath.getText());          
                    BufferedReader b = new BufferedReader(new FileReader(f));                    
                    String readLine = "";  
                    int linecounter = 0;
                    while ((readLine = b.readLine()) != null) {
                        if (linecounter != 0){                        
                            String[] parts = readLine.replaceAll("\\s+", "").split("<");
                            String part1 = parts[1].trim();
                            String part2 = parts[2].trim();
                            String part3 = parts[3].trim();      
                            String part4 = parts[4].trim();
                            String part5 = parts[5].trim();
                            model.addRow(new Object[]{Integer.parseInt(part1.replaceAll(">", "")), Integer.parseInt(part2.replaceAll(">", "")), Integer.parseInt(part3.replaceAll(">", "")),null,null,null,null,Integer.parseInt(part4.replaceAll(">", "")),Integer.parseInt(part5.replaceAll(">", ""))});                               
                    }
                    linecounter++;
            }            
                }    
                catch (IOException e) {
                    e.printStackTrace();
                }
            }
        
            doneflag = false;
            qIndicator = 0;
           if(Datas.getRowCount()>0){
               jobList[] JOB = new jobList[50]; //max 50 objects
               for(int i = 0; i < Datas.getRowCount(); i++){
                    JOB[i] = new jobList();
                    JOB[i].ID = Integer.parseInt(Datas.getValueAt(i, 0).toString());                    
               }
           }
           startbtn.setEnabled(true);
           stopbtn.setEnabled(false);
           jButton3.setEnabled(false);
           jButton5.setEnabled(false);
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //PAUSE
        jButton3.setEnabled(false);
        jButton5.setEnabled(true);
        if(FilePath.getText().length()>0){
        t.stop();
        t.setDelay(Integer.parseInt(delaySelector.getSelectedItem().toString()));}      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stopbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtnActionPerformed
      // RESET ALL VARIABLES
        try{
            startbtn.setEnabled(false);
            
            temp = 0;
            counter = 0;
            currentjob = 0;
            totalNumberOfJobs = 0;
            indexCount = 0;
            FilePath.setText(null);
            cpuBox.setText("-");
            DefaultTableModel model = (DefaultTableModel) Datas.getModel();
            model.setRowCount(0);
            DefaultTableModel model2 = (DefaultTableModel) Gantt.getModel();
            startbtn.setEnabled(true);
            AWT.setText("0");
            ATT.setText("0");
            model2.setRowCount(0);
            DefaultTableModel model3 = (DefaultTableModel) Q1.getModel();
            model3.setRowCount(0);
            DefaultTableModel model4 = (DefaultTableModel) Q2.getModel();
            model4.setRowCount(0);
            DefaultTableModel model5 = (DefaultTableModel) Q3.getModel();
            model5.setRowCount(0);
            DefaultTableModel model6 = (DefaultTableModel) inputQueue.getModel();
            model6.setRowCount(0);
            currentSeconds.setText(String.valueOf(counter));
            clearmemory();
            this.invalidate();
            this.validate();
            this.repaint();t.stop();
            
      }
      catch(NullPointerException e ){
            JOptionPane.showMessageDialog(this, e, null, WIDTH);

      }
    }//GEN-LAST:event_stopbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //RESUME
        jButton3.setEnabled(true);
        jButton5.setEnabled(false);
        if(FilePath.getText().length()>0){
            t.start();
       }       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilePathActionPerformed

    private void FilePathPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FilePathPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_FilePathPropertyChange

    private void delaySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delaySelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delaySelectorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      //INITIALIZE DELAY SELECTOR
        for (int i = 1000; i > 0; i--){
          delaySelector.addItem(String.valueOf(i));
      }
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
   //CHECK IF JOBS ARE VALID 
    public boolean JobCheck(String FileName){
        try{
            File f = new File(FileName);
            BufferedReader b = new BufferedReader(new FileReader(f));
            String readLine ="";
            int linecounter = 0, supposejobs = 0;
          
            while ((readLine = b.readLine()) != null) {               
                if (linecounter == 0){                   
                    
                    String[] parts = readLine.replaceAll(" ","").split("<");
                      
                    String part1 = parts[1];
                    supposejobs = Integer.parseInt(part1.replaceAll(">", ""));                    
                }
                else{
                    String[] parts = readLine.split("<");
                     if (Integer.parseInt(parts[5].trim().replaceAll(">", ""))>16){                           
                            JOptionPane.showMessageDialog(this, "One/more job has memory requirement larger than 16K.", null, WIDTH);
                            return false;
                        }
                    if (Integer.parseInt(parts[1].trim().replaceAll(">", ""))>90 || Integer.parseInt(parts[2].trim().replaceAll(">", ""))>60||Integer.parseInt(parts[3].trim().replaceAll(">", ""))>20||Integer.parseInt(parts[4].trim().replaceAll(">", ""))>3||Integer.parseInt(parts[4].trim().replaceAll(">", ""))<1) {

                            JOptionPane.showMessageDialog(this, "One/more job has invalid value.", null, WIDTH);
                        
                        return false;
                    }               
                }
                if(linecounter-1 > 20){
                        JOptionPane.showMessageDialog(this, "Reached Max. number of Jobs(20).", null, WIDTH);
                        return false;
                    }
                linecounter++;
            }         
            if(linecounter-1 != supposejobs){
                JOptionPane.showMessageDialog(this, "Supposed number of jobs does not meet the actual number of jobs.", null, WIDTH);
                return false;
            }
            else{
                return true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "One column of data is missing.. must be <JOB><AT><CBT><JOBTYPE>", null, WIDTH);
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPU_with_MFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPU_with_MFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPU_with_MFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPU_with_MFT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPU_with_MFT().setVisible(true);          
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATT;
    private javax.swing.JLabel AWT;
    private javax.swing.JTable Datas;
    private javax.swing.JTextField FilePath;
    private javax.swing.JTable Gantt;
    private javax.swing.JTextPane K16_1;
    private javax.swing.JTextPane K16_2;
    private javax.swing.JTextPane K4_1;
    private javax.swing.JTextPane K4_2;
    private javax.swing.JTextPane K8_1;
    private javax.swing.JTextPane K8_2;
    private javax.swing.JTextPane K8_3;
    private javax.swing.JTable Q1;
    private javax.swing.JTable Q2;
    private javax.swing.JTable Q3;
    private javax.swing.JTextField cpuBox;
    private javax.swing.JLabel currentSeconds;
    private javax.swing.JComboBox<String> delaySelector;
    private javax.swing.JTable inputQueue;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JButton startbtn;
    private javax.swing.JButton stopbtn;
    // End of variables declaration//GEN-END:variables
}